
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/app/extra/clion/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.10.10-arch1-1 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/app/extra/clion/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:1165 (message)"
      - "/app/extra/clion/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineCUDACompiler.cmake:75 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Checking whether the CUDA compiler is NVIDIA using "" matched "nvcc: NVIDIA \\(R\\) Cuda compiler driver":
      nvcc: NVIDIA (R) Cuda compiler driver
      Copyright (c) 2005-2024 NVIDIA Corporation
      Built on Wed_Aug_14_10:10:22_PDT_2024
      Cuda compilation tools, release 12.6, V12.6.68
      Build cuda_12.6.r12.6/compiler.34714021_0
...
